[workspace]
resolver = "2"
members = [
    "rune-core",
    "rune-adapters/uri",
    "rune-adapters/aegis",
    "rune-adapters/twofas",
    "rune-adapters/kdbx",
    "rune-cli",
    "rune-desktop",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Rune Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/theaayushpatel/rune"

[workspace.dependencies]
rune-core = { path = "rune-core" }
rune-adapter-uri = { path = "rune-adapters/uri" }
rune-adapter-aegis = { path = "rune-adapters/aegis" }
rune-adapter-twofas = { path = "rune-adapters/twofas" }
rune-adapter-kdbx = { path = "rune-adapters/kdbx" }

keepass = { version = "0.13", features = ["save_kdbx4"] }
pbkdf2 = "0.12"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
zeroize = { version = "1.8", features = ["derive"] }
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
data-encoding = "2.6"
fuzzy-matcher = "0.3"
url = "2.5"
percent-encoding = "2.3"
aes-gcm = "0.10"
scrypt = "0.11"
base64 = "0.22"
hex = "0.4"
clap = { version = "4.5", features = ["derive"] }
arboard = "3.4"
colored = "2.1"
crossterm = "0.28"
rpassword = "7.3"
tokio = { version = "1.40", features = ["full"] }
eframe = "0.31"
