[package]
name = "rune-adapter-kdbx"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rune-core.workspace = true
rune-adapter-uri.workspace = true
keepass.workspace = true
thiserror.workspace = true
url.workspace = true
zeroize.workspace = true
hex.workspace = true
data-encoding.workspace = true
uuid = "1"
